{
    'name': 'Student contract management',
    'version': '1.0.0',
    'sequence': -100,
    'author': 'Jhonny Rivas',
    'website': 'www.jhonnyrivas.com',
    'category': 'Health',
    'summary': 'Student contract management',
    'description': 'Student contract management info',
    'depends': ['base', 'website','web', 'board'],
    'data': [
        'security/ir.model.access.csv',
        'data/student_data.xml',
         'data/career_data.xml',
        'data/subject_data_option.xml',
        'data/professor_data.xml',
        'data/subject_data.xml',
        # 'data/student_contract_data.xml',
         'views/assets_backend.xml',
        'views/student_dashboard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'student_contract_management/static/src/js/dashboard_graphs.js',
            'https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js',
            'student_contract_management/static/src/css/dashboard.css',
        ],
    },
    'qweb': [],
    'installable':True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}